_check-cwd
git-svn-id: https://svn.amooma.com/gemeinschaft/trunk@5415 2d91074e-20bd-43ae-8273-9033e1f9829e

diff --git a/opt/gemeinschaft/locale/Makefile b/opt/gemeinschaft/locale/Makefile
--- a/opt/gemeinschaft/locale/Makefile
+++ b/opt/gemeinschaft/locale/Makefile
@@ -8,9 +8,9 @@ COPYRIGHT_HOLDER=Amooma GmbH, http://www.amooma.de
 GETTEXT_DOMAIN=gemeinschaft-gui
 
 
-help:
+help: _check-cwd
 	@echo ""
-	@echo "Attention! Run make in /usr/src/gemeinschaft-trunk/opt/gemeinschaft/locale"
+	@echo "Note: Run make in /usr/src/gemeinschaft-trunk/opt/gemeinschaft/locale"
 	@echo "(not /opt/gemeinschaft/locale)"
 	@echo ""
 	@echo "Targets:"
@@ -18,7 +18,15 @@ help:
 	@echo "  make all       : Generate .php and .mo files"
 	@echo ""
 
-_pot:
+_check-cwd:
+	@ if [ "x$${PWD}" = "x/opt/gemeinschaft/locale" ]; then \
+		echo "Error."; \
+		echo "Run make in /usr/src/gemeinschaft-trunk/opt/gemeinschaft/locale"; \
+		echo "(not /opt/gemeinschaft/locale)"; \
+		exit 1; \
+	fi
+
+_pot: _check-cwd
 	@echo "### Generating the .pot (.po template) ..."
 	cd ${GEMEINSCHAFT_TAG_ROOT} \
 	&& find . -type f \
@@ -29,14 +37,14 @@ _pot:
 	| xargs -0 grep -I -l '__(' \
 	| xgettext -f - -L 'PHP' -d '${GETTEXT_DOMAIN}' -o '${DIR}/pot/${GETTEXT_DOMAIN}.pot' --copyright-holder='${COPYRIGHT_HOLDER}' --keyword='__' --from-code='UTF-8' -n -s --strict
 
-sort-po:
+sort-po: _check-cwd
 	@for LANGDIR in ${LANGS} ;\
 	do \
 		echo "### Sorting strings in $${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po ..." ;\
 		msgcat -n -s --strict -o "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po" "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po" ;\
 	done
 
-update-po: _pot
+update-po: _check-cwd _pot
 	@for LANGDIR in ${LANGS} ;\
 	do \
 		echo "### Merging ${GETTEXT_DOMAIN}.pot into $${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po ..." ;\
@@ -46,19 +54,19 @@ update-po: _pot
 		mv "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po.uniq" "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po" ;\
 	done
 
-gen-mo:
+gen-mo: _check-cwd
 	@for LANGDIR in ${LANGS} ;\
 	do \
 		echo "### Generating $${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.mo ..." ;\
 		msgfmt -c --strict --statistics -o "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.mo" "$${LANGDIR}/LC_MESSAGES/${GETTEXT_DOMAIN}.po" ;\
 	done
 
-gen-php:
+gen-php: _check-cwd
 	@echo "### Generating the .php files ..."
 	./po-to-php.php
 
 all: gen-mo gen-php
 
 
-.PHONY: help _pot update-po gen-mo gen-php all
+.PHONY: help _check-cwd _pot update-po gen-mo gen-php all
 
